# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52039aa47d3699642fd6d19a5093b36c0a50b680b9da67166095041135ab73175844b097207dcf334bea622290828b6b626ad65d98a374d6f356fcc3f8dc5d24

test:
  secret_key_base: d1e90b9e990c9ee0544c50e1d0f4ce4a67bb38b72d077b946b785724be6c83ef2e68ce723d0d228c5814c17b07da4448bfbd21a7045385dc4be800f941eb1858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
